apiVersion: v1
kind: ConfigMap
metadata:
  name: fulfillment-service-config-prod
  namespace: prod
data:
  SERVER_PORT: "8085"
  SPRING_APPLICATION_NAME: "fulfillment-service"
  SPRING_PROFILES_ACTIVE: "prod"
  SPRINGDOC_API_DOCS_PATH: "/api-docs"
  SPRINGDOC_SWAGGER_UI_PATH: "/swagger-ui.html"
  LOGGING_LEVEL_FULFILLMENT: "WARN"
  LOGGING_LEVEL_SPRING: "WARN"
  LOGGING_LEVEL_HIBERNATE: "WARN"
  LOGGING_LEVEL_ROOT: "WARN"
  MANAGEMENT_ENDPOINTS_INCLUDE: "health,info"
  MANAGEMENT_HEALTH_SHOW_DETAILS: "never"