apiVersion: v1
kind: Service
metadata:
  name: fulfillment-service
  namespace: default
  labels:
    app: fulfillment-service
spec:
  type: ClusterIP
  ports:
  - port: 8085
    targetPort: 8085
    protocol: TCP
    name: http
  selector:
    app: fulfillment-service