server:
  port: 8890
  servlet:
    context-path: /

spring:
  application:
    name: product-catalog-service

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    packages-to-scan: com.ecommapp.productcatalogservice.controller